FROM postgres:15.1-alpine

# NOTE: No need to create raw_transfers tables at the time because it will created automatically in the mage data-exporter logic
# COPY ./init.sql /docker-entrypoint-initdb.d/init.sql
# RUN chmod +x /docker-entrypoint-initdb.d/init.sql

EXPOSE 5432