version: '3'

services:

#####################################################
# APP SERVICE
######################################################

  mage:
    build:
      context: ./docker/mage
    container_name: mage
    ports:
      - 6789:6789
    volumes:
      - ./docker/mage/transfermarkt:/opt/mage/app
      - ~/.aws:/root/.aws
      - ~/.mage_data:/root/.mage_data

#####################################################
# DATABASE SERVICE
######################################################
  postgres:
    build: 
      context: ./docker/postgres
    restart: always
    container_name: postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    ports:
      - "32769:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=transfermarkt
      - POSTGRES_PASSWORD=transfermarkt
      - POSTGRES_DB=transfermarkt_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "transfermarkt_db", "-U", "transfermarkt" ]
      timeout: 45s
      interval: 10s
      retries: 10

  adminer:
    build: 
      context: ./docker/adminer
    restart: always
    container_name: adminer
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    ports:
      - "9000:9000"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=transfermarkt_db
    healthcheck:
      test: [ "CMD", "nc", "-z", "adminer", "9000" ]
      timeout: 45s
      interval: 10s
      retries: 10