blocks:
- all_upstream_blocks_executed: true
  configuration: {}
  downstream_blocks:
  - fill_in_missing_values
  - fill_in_missing_values
  executor_config: null
  executor_type: local_python
  language: python
  name: load_titanic
  status: not_executed
  type: data_loader
  upstream_blocks: []
  uuid: load_titanic
- all_upstream_blocks_executed: false
  configuration: {}
  downstream_blocks:
  - export_titanic_clean
  executor_config: null
  executor_type: local_python
  language: python
  name: fill_in_missing_values
  status: not_executed
  type: transformer
  upstream_blocks:
  - load_titanic
  uuid: fill_in_missing_values
- all_upstream_blocks_executed: false
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  language: python
  name: export_titanic_clean
  status: not_executed
  type: data_exporter
  upstream_blocks:
  - fill_in_missing_values
  uuid: export_titanic_clean
data_integration: null
name: example_pipeline
type: python
uuid: example_pipeline
widgets: []
